version: 2
on;
   workflow_dispatch:
   
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "hourly"
    open-pull-requests-limit: 10
